name: BuildinTypesCheck

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Script
      run: |
        chmod +x ./Core/BuildinTypesUpdater.sh
        ./Core/BuildinTypesUpdater.sh
