name: BuildinTypesCheck

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Script
      run: |
        chmod +x ./Core/BuildinTypesUpdater.sh
        ./Core/BuildinTypesUpdater.sh
        
    - name: Commit and Push Changes
      run: |
        git config --global user.email "danielmolinero111@cyberdude.com"
        git config --global user.name "Papishushi"
        git add .
        git commit -m "Update BuildinTypes.xml via GitHub Actions"
        git push
